name: Deployment
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master

    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x

    - name: Build
      env:
        DOMAIN: explorer.libplanet.io
      run: |
        npm install
        mkdir -p _site
        echo "$DOMAIN" > _site/CNAME
        while IFS=$'\t' read -r -a tuple; do
          {
            echo PATH_PREFIX="/${tuple[0]}"
            echo NETWORK_NAME="${tuple[0]}"
            echo GRAPHQL_ENDPOINT_URI="${tuple[1]}"
          } > .env.production
          npm run build
          mv public "_site/${tuple[0]}"
          if [[ ! -f _site/index.html ]]; then
            if [[ "${tuple[1]}" = https* ]]; then
              url="https://$DOMAIN/${tuple[0]}/"
            else
              url="http://$DOMAIN/${tuple[0]}/"
            fi
            echo "${tuple[0]} -> ${tuple[1]}"
            echo $url
            {
              echo '<!DOCTYPE html>'
              echo '<html><head><meta charset="utf-8">'
              echo '<meta http-equiv="refresh" content="0;' \
                   "$url"'">'
              echo '<title>Libplanet Explorer</title>'
              echo '<link rel="canonical" href="'"$url"'">'
              echo '</head><body>'
              echo '</body>'
            } > _site/index.html
          fi
        done < DEPLOYMENTS.tsv
  
    - name: Publish
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: _site/
        GH_PAT: ${{ secrets.GH_PAT }}

    - name: Trigger GitHub Pages Build
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
      run: |
        curl -X POST \
             -H "Authorization: token $GH_PAT" \
             -H "Accept: application/vnd.github.mister-fantastic-preview+json" \
             "https://api.github.com/repos/$GITHUB_REPOSITORY/pages/builds"